# Generated by Django 2.0.4 on 2018-06-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='twit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.FileField(default='SOME STRING', upload_to='')),
            ],
        ),
    ]
